### ISSUE TITLE
Shopware POS x MultiSafepay

### ISSUE THREAD

**Issue by rj058** [MultiSafepay/Shopware#8]
Pickware POS cannot add an order in shopware. No payment by Multisafepay is needed for this order. 

The issue started after this multisafepay update: PLGSHPS-223: Add support for the PHP-SDK
Version 2.10.0 is still functional

`plugin.ERROR: ViisonPickwarePOS: Failed to create order via REST API {"exception":"[object] (MultiSafepay\\Exception\\ApiException(code: 405): Method not allowed at /home/***/public_html/custom/plugins/MltisafeMultiSafepayPayment/vendor/multisafepay/php-sdk/src/Api/Base/Response.php:98)"} {"uid":"ef95a5c"}`

**Comment by Daniel-MultiSafepay** [comment]
Hi @rj058 . 

Thanks for reaching us. It seems one of my colleagues from support, made a mistake in asking you to report this via GitHub; because to resolve this we need to have more information and since this is a public space, it is not appropriate to share information that might be sensitive to the security of your application. 

We hope to continue this through our internal ticket system.
